### ISSUE TITLE
Xavier NX Devkit .... is the following required?

### ISSUE THREAD

**Issue by outbackdingo** [madisongh/digsigserver#2]
If you are supporting Jetson TX2 or Jetson AGX Xavier devices that use both PKC signing and SBK encryption of bootloader files, you will also need to apply a patch from meta-tegra:

$ P=/path/to/meta-tegra/recipes-bsp/tegra-binaries/files
$ cd /opt/nvidia/L4T-32.2.3-tegra186/Linux_for_Tegra
$ sudo patch -p1 < $P/0002-Update-l4t_bup_gen.func-to-handle-signed-encrypted-b.patch

**Comment by madisongh** [comment]
It depends on the version of L4T you are targeting.  NVIDIA fixed the PKC+SBK support in their tools in R32.4.3, so that particular patch is not required. There is [this one](https://github.com/OE4T/meta-tegra/blob/master/recipes-bsp/tegra-binaries/files/0002-Fix-typo-in-l4t_bup_gen.func.patch), though, which you do need to fix a typo in the `l4t_bup_gen.func` script.   And if you want the scripts to run under Python 3, you'll need the Python 3 conversion patches mentioned in the [tegra186-flashtools-native](https://github.com/OE4T/meta-tegra/blob/master/recipes-bsp/tegra-binaries/tegra186-flashtools-native_32.4.3.bb) recipe.

**Comment by outbackdingo** [comment]
My target is R32.4.3 on the Xavier NX, youll see im hammering through it in the other encrypted rootfs secure boot thread. Ill work this out with your suggestions! Thx

**Comment by outbackdingo** [comment]
so apply all but 001 .... got it!

**Comment by outbackdingo** [comment]
done
